
### create a report
POST http://localhost:3000/report
content-type: application/json

{
   "make": "toyota",
   "model": "corolla",
   "year": 1980,
   "mileage": 10000,
   "lng": 0,
   "lat": 0,
   "price": 10000 
}

### estimate a vehicle
GET http://localhost:3000/report?make=toyota&model=corolla&year=1980&mileage=10000&lng=0&lat=0

### approve a report
PATCH  http://localhost:3000/report/8
content-type: application/json

{
    "approved": true
}